### ISSUE TITLE
_get_file_path() cannot handle DMA codes as integers

### ISSUE THREAD

**Issue by gserapio** [pewresearch/search_sampler#1]
First of all, this is a great package. A big thanks to the talented people at Pew Research for putting this out there.

It seems like the function `_get_file_path()` in `search_sampler/_init_.py` is rejecting DMA codes since the codes are stored as integers. At line 144:
```
str_path = os.path.join(self.output_path, self.params["region"])
```

Issue can be reproduced by running `example.py` with the 'region' parameter set to `500` (without quotes):
```
TypeError: join() argument must be str or bytes, not 'int'
```

Note that the issue can't be fixed by setting the 'region' parameter to `'500'` (as a string) because `pull_data_from_api()` requires `params['region']` to be an integer.

**Comment by GalenStocking** [comment]
Thanks for bringing this to our attention! We've implemented a fix that should address this - please let us know if it does not.

**Comment by gserapio** [comment]
Thank you, this fix worked great!
